version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    command: bash -c "poetry run python3 src/app/main.py"
    restart: always
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5435:5432"
    restart: always

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9090:9090"
    env_file:
      - .env
    command: server --console-address :9090 /data
    volumes:
      - ./minio/data:/data
      - ./minio/conf:/root/.minio
